wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1636559654
    t:
      3:
      - 2
      4: 3.7.9
      5: 0.12.6
      8:
      - 3
      - 5
