wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1636647277
    t:
      4: 3.7.9
      5: 0.12.6
      8:
      - 1
      - 3
      - 5
