name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pandas=1.3.1
  - mlflow=1.14.1
  - hydra-core=1.0.6
  - pip=21.3.1
  - wandb=0.12.7
  - pip:
      - wandb==0.12.7